export const postQuery = `*[_type == "post"] | order(_createdAt desc)
{
  thumbnail{
      asset->{
        url
      }
    },
    _id,
    about,
    liveUrl,
    gitHubUrl,
    completionTime,
    postedBy->{
          _id,
      userName,
      image
    },
  } 
`;